export const POST_BAG_REQUEST = "POST_BAG_REQUEST";
export const POST_BAG_SUCCESS = "POST_BAG_SUCCESS";
export const POST_BAG_FAILURE = "POST_BAG_FAILURE";

export const GET_BAG_REQUEST = "GET_BAG_REQUEST";
export const GET_BAG_SUCCESS = "GET_BAG_SUCCESS";
export const GET_BAG_FAILURE = "GET_BAG_FAILURE";

export const DELETE_BAG_REQUEST = "DELETE_BAG_REQUEST";
export const DELETE_BAG_SUCCESS = "DELETE_BAG_SUCCESS";
export const DELETE_BAG_FAILURE = "DELETE_BAG_FAILURE";

export const PATCH_BAG_REQUEST = "PATCH_BAG_REQUEST";
export const PATCH_BAG_SUCCESS = "PATCH_BAG_SUCCESS";
export const PATCH_BAG_FAILURE = "PATCH_BAG_FAILURE";


export const INCREASE_BAG_QTY = "INCREASE_BAG_QTY";

export const DECREASE_BAG_QTY = "DECREASE_BAG_QTY";

